### ISSUE TITLE
Line 2 of Requirements broken (404)

### ISSUE THREAD

**Issue by abrutus** [tag1consulting/hphp#3]
IUS: 'rpm -ivh http://dl.iuscommunity.org/pub/ius/stable/Redhat/5/x86_64/ius-release-1.0-6.ius.el5.noarch.rpm'

Yields a 404.

**Comment by jeffsheltren** [comment]
ius-release has been updated -- the URL for the latest package is now: http://dl.iuscommunity.org/pub/ius/stable/Redhat/5/x86_64/ius-release-1.0-10.ius.el5.noarch.rpm

I'll update the readme shortly.
